In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics import roc_curve
from scipy import optimize
import math as mt

Using TensorFlow backend.


In [2]:
ev_1 = pd.read_hdf('../../data0/users/jisaacson/TrackML/events_200.h5').iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,18,19]]
evv = ev_1.loc[(ev_1['volume_id']==8)]
a = [str(i) for i in np.arange(1131, 1171)]
ev = evv[evv['event_id'].isin(a)]
ev

event_id  hit_id           x           y           z  volume_id  \
13884     1131   13885  -30.164200  -10.485100 -426.817993          8   
13885     1131   13886  -30.367599   -9.903200 -424.893005          8   
13886     1131   13887  -25.203300  -19.721500 -488.829987          8   
13887     1131   13888  -22.718500  -24.501200 -475.597992          8   
13888     1131   13889  -21.256300  -25.205799 -473.839996          8   
13889     1131   13890    2.671180  -32.896198 -474.114990          8   
13890     1131   13891    5.124220  -32.038502 -467.826996          8   
13891     1131   13892   29.511999  -12.320100 -424.079010          8   
13892     1131   13893   32.567699    3.610520 -431.597992          8   
13893     1131   13894   24.860001   23.469299 -445.183990          8   
13894     1131   13895   10.376500   30.448601 -434.444000          8   
13895     1131   13896   24.393299   23.694201 -463.428009          8   
13896     1131   13897   12.128700   29.604200 -489.213989          8   
13897     1131   13898    9.664460   31.440100 -445.330994          8   
13898     1131   13899   10.178300   31.411100 -465.260010          8   
13899     1131   13900   -2.569320   32.931801 -452.272003          8   
13900     1131   13901   -7.748280   31.121000 -463.662994          8   
13901     1131   13902   -2.934060   32.804298 -447.661011          8   
13902     1131   13903  -13.417300   30.834200 -426.737000          8   
13903     1131   13904  -19.329000   25.553801 -437.537994          8   
13904     1131   13905  -24.761700   22.177999 -466.523987          8   
13905     1131   13906  -24.874100   21.944700 -472.864990          8   
13906     1131   13907  -31.751499    4.143360 -480.093994          8   
13907     1131   13908  -31.746599    4.229950 -451.076996          8   
13908     1131   13909  -31.683800    5.342940 -455.062988          8   
13909     1131   13910  -30.515100   -7.981130 -386.479004          8   
13910     1131   13911  -28.857201  -12.723000 -394.321014          8   
13911     1131   13912  -33.668098    1.036820 -405.778992          8   
13912     1131   13913  -29.566999  -14.092800 -356.924988          8   
13913     1131   13914  -26.157801  -17.909599 -374.958008          8   
...        ...     ...         ...         ...         ...        ...   
38197     1170   38198 -142.468002   95.326500  435.260986          8   
38198     1170   38199 -139.003998  102.247002  484.919006          8   
38199     1170   38200 -145.007996   90.254303  446.277008          8   
38200     1170   38201 -143.268997   93.726196  446.261993          8   
38201     1170   38202 -141.261002   97.737297  457.834991          8   
38202     1170   38203 -144.300003   91.666603  462.472992          8   
38203     1170   38204 -146.479004   91.477501  451.244995          8   
38204     1170   38205 -148.850006   85.603203  420.928986          8   
38205     1170   38206 -147.076996   89.994499  426.313995          8   
38206     1170   38207 -146.975998   90.244301  477.220001          8   
38207     1170   38208 -147.259003   89.544296  421.964996          8   
38208     1170   38209 -162.212006   53.730598  441.971008          8   
38209     1170   38210 -161.281006   57.845501  443.502991          8   
38210     1170   38211 -165.128006   46.668098  443.114990          8   
38211     1170   38212 -164.492996   51.112598  465.574005          8   
38212     1170   38213 -165.796005   41.999500  429.216003          8   
38213     1170   38214 -164.007004   54.514099  447.239990          8   
38214     1170   38215 -164.964005   47.815498  460.588989          8   
38215     1170   38216 -168.487000   30.966999  446.223999          8   
38216     1170   38217 -168.216995   35.369598  455.572998          8   
38217     1170   38218 -168.192001   35.770000  432.545013          8   
38218     1170   38219 -168.350006   33.201599  423.238007          8   
38219     1170   38220 -168.184006   35.908401  459.941010      

In [3]:
def eta_calculation(x, y, z):
    r = np.sqrt(x**2 + y**2 + z**2)
    theta = np.arccos(z/r)
    eta = -np.log(np.tan(theta/2.0))
    return eta
etas = []
df = pd.DataFrame()
for i in range(len(ev)):
    dat = ev.iloc[i, :]
    eta = eta_calculation(dat['x'], dat['y'], dat['z'])
    if np.absolute(eta) <= 1.2:
        etas.append(eta)
        df = df.append(dat)
df.insert(2, 'eta', etas)
df.to_pickle('final_data7_cut.pkl')
df = pd.read_pickle('final_data7_cut.pkl')


In [4]:
particle_ids = df['particle_id'].unique()
df

event_id   hit_id       eta  layer_id  module_id  nch0  nch1  \
15959     1131  15960.0 -0.646519       2.0       97.0   3.0   1.0   
15961     1131  15962.0 -0.567554       2.0       97.0   1.0   2.0   
15964     1131  15965.0 -0.836063       2.0       97.0   1.0   6.0   
15965     1131  15966.0  0.019401       2.0       97.0   2.0   4.0   
15966     1131  15967.0 -0.227065       2.0       97.0   2.0   5.0   
15967     1131  15968.0 -0.705759       2.0       97.0   2.0   9.0   
15968     1131  15969.0 -0.917714       2.0       97.0   2.0   2.0   
15970     1131  15971.0 -1.087182       2.0       97.0   1.0   4.0   
15971     1131  15972.0 -0.601924       2.0       97.0   2.0   3.0   
15972     1131  15973.0 -0.030813       2.0       97.0   3.0   3.0   
15973     1131  15974.0 -1.092052       2.0       97.0   2.0   1.0   
15976     1131  15977.0 -0.115415       2.0       97.0   1.0   3.0   
15977     1131  15978.0 -0.004642       2.0       97.0   2.0   1.0   
15978     1131  15979.0 -0.371835       2.0       97.0   3.0   4.0   
15979     1131  15980.0 -0.723858       2.0       97.0   1.0   3.0   
15980     1131  15981.0 -0.791960       2.0       97.0   2.0   3.0   
15981     1131  15982.0 -0.053546       2.0       97.0   2.0   4.0   
15982     1131  15983.0 -0.912730       2.0       97.0   2.0   1.0   
15984     1131  15985.0 -0.857859       2.0       97.0   2.0   3.0   
15985     1131  15986.0 -1.130951       2.0       97.0   2.0   3.0   
15988     1131  15989.0 -0.765982       2.0       97.0   1.0   3.0   
15989     1131  15990.0 -0.533814       2.0       97.0   1.0   4.0   
15990     1131  15991.0 -0.317356       2.0       97.0   2.0   2.0   
15991     1131  15992.0 -0.969746       2.0       97.0   2.0  10.0   
15993     1131  15994.0 -0.407597       2.0       97.0   3.0   9.0   
15995     1131  15996.0 -1.126916       2.0       97.0   1.0   1.0   
15996     1131  15997.0  0.030216       2.0       97.0   1.0   1.0   
16000     1131  16001.0 -1.105303       2.0       97.0   1.0   5.0   
16001     1131  16002.0 -0.999857       2.0       97.0   1.0   5.0   
16002     1131  16003.0 -1.154345       2.0       97.0   2.0   6.0   
...        ...      ...       ...       ...        ...   ...   ...   
37373     1170  37374.0  1.027493       8.0      850.0   1.0   3.0   
37374     1170  37375.0  1.123848       8.0      850.0   2.0   4.0   
37375     1170  37376.0  1.180287       8.0      850.0   8.0   5.0   
37376     1170  37377.0  1.175107       8.0      850.0   3.0   5.0   
37377     1170  37378.0  1.165648       8.0      851.0   2.0   4.0   
37378     1170  37379.0  1.111769       8.0      851.0   1.0   3.0   
37379     1170  37380.0  1.066886       8.0      851.0   2.0   5.0   
37381     1170  37382.0  1.034494       8.0      851.0   3.0   3.0   
37382     1170  37383.0  1.187613       8.0      852.0   1.0   5.0   
37383     1170  37384.0  1.102539       8.0      852.0   2.0   5.0   
37385     1170  37386.0  1.079124       8.0      852.0   1.0   4.0   
37386     1170  37387.0  1.111426       8.0      852.0   6.0   1.0   
37387     1170  37388.0  1.093961       8.0      852.0   2.0   5.0   
37388     1170  37389.0  1.137468       8.0      852.0   2.0   5.0   
37390     1170  37391.0  1.158962       8.0      853.0   2.0   4.0   
37391     1170  37392.0  1.114206       8.0      853.0   2.0   3.0   
37392     1170  37393.0  1.060507       8.0      853.0   1.0   4.0   
37393     1170  37394.0  1.157412       8.0      854.0   3.0   4.0   
37394     1170  37395.0  1.153543       8.0      854.0   4.0   7.0   
37395     1170  37396.0  1.116015       8.0      854.0   2.0   5.0   
37396     1170  37397.0  1.131634       8.0      854.0   3.0   6.0   
37397     1170  37398.0  1.060659       8.0      854.0   1.0   5.0   
37398     1170  37399.0  1.125758       8.0      854.0   1.0   5.0   
37401     1170  37402.0  1.115712       8.0      855.0   2.0   4.0   
37403     1170  37404.0  1.096121       8.0      855.0   2.0   2.0   
37404     1170  

In [5]:
dff = pd.DataFrame()
for i in particle_ids:
    par_info = df.loc[df['particle_id'] == i]
    event_indicator = pd.DataFrame(par_info['event_id'].value_counts().sort_index())
    
    event_ids = np.array([j for j in event_indicator.loc[event_indicator['event_id'] >= 3].index])
    for j in event_ids:
        particle_info = par_info.loc[par_info['event_id'] == j]
        layer_indicator = particle_info['layer_id'].value_counts().sort_index()
        if i != 0 and len(layer_indicator) >= 3 and (sum(np.array(layer_indicator.index)) == 12 or sum(np.array(layer_indicator.index)) == 20):
            dff = dff.append(particle_info)
##looking for event of a particle with at least 3 hits 
##for such event, check it has at least one hit per layer on layer_id 2, layer_id 4, and layer_id 6; 2+4+6 == 12 and 2+4+6+8 == 20 
dff.to_pickle('ideal_final_data7_cut.pkl')

In [6]:
ideal_particle_ids = dff['particle_id'].unique()
dff

event_id   hit_id       eta  layer_id  module_id  nch0  nch1  \
15959     1131  15960.0 -0.646519       2.0       97.0   3.0   1.0   
17304     1131  17305.0 -0.667373       2.0      112.0   1.0   2.0   
23406     1131  23407.0 -0.383055       4.0      193.0   1.0   1.0   
29511     1131  29512.0 -0.293873       6.0      313.0   1.0   1.0   
34971     1131  34972.0 -0.243260       8.0      470.0   2.0   1.0   
15961     1131  15962.0 -0.567554       2.0       97.0   1.0   2.0   
16115     1131  16116.0 -0.547738       2.0       98.0   2.0   1.0   
23421     1131  23422.0 -0.308945       4.0      194.0   1.0   1.0   
23445     1131  23446.0 -0.302989       4.0      195.0   3.0   2.0   
29540     1131  29541.0 -0.226089       6.0      315.0   2.0   1.0   
34985     1131  34986.0 -0.182257       8.0      472.0   2.0   1.0   
14114     1137  14115.0 -0.290767       2.0      101.0   2.0   4.0   
20693     1137  20694.0 -0.668863       4.0      201.0   2.0   3.0   
25764     1137  25765.0 -0.773824       6.0      274.0   2.0   4.0   
25772     1137  25773.0 -0.776807       6.0      275.0   2.0   4.0   
30535     1137  30536.0 -0.831035       8.0      333.0   2.0   4.0   
21504     1141  21505.0 -0.515294       2.0      106.0   2.0   1.0   
21693     1141  21694.0 -0.491164       2.0      107.0   3.0   1.0   
30680     1141  30681.0 -0.313487       4.0      212.0   1.0   1.0   
38318     1141  38319.0 -0.247448       6.0      345.0   2.0   1.0   
45082     1141  45083.0 -0.214005       8.0      516.0   2.0   1.0   
45087     1141  45088.0 -0.213106       8.0      517.0   2.0   2.0   
17580     1159  17581.0 -0.950816       2.0      105.0   2.0   5.0   
17646     1159  17647.0 -0.854585       2.0      106.0   3.0   4.0   
25219     1159  25220.0  0.197409       4.0      242.0   1.0   4.0   
30884     1159  30885.0  0.571028       6.0      393.0   1.0   4.0   
31452     1159  31453.0  0.573468       6.0      445.0   2.0   5.0   
31478     1159  31479.0  0.583119       6.0      446.0   2.0   4.0   
37005     1159  37006.0  0.748061       8.0      746.0   2.0   5.0   
22510     1164  22511.0  0.344464       2.0      127.0   2.0   2.0   
...        ...      ...       ...       ...        ...   ...   ...   
18929     1170  18930.0  0.053134       2.0      128.0   1.0   1.0   
25157     1170  25158.0  0.078967       4.0      256.0   2.0   1.0   
30805     1170  30806.0  0.086294       6.0      416.0   2.0   2.0   
36138     1170  36139.0  0.090390       8.0      623.0   2.0   1.0   
18939     1170  18940.0  0.446481       2.0      128.0   1.0   2.0   
25140     1170  25141.0  0.440002       4.0      256.0   1.0   2.0   
30806     1170  30807.0  0.439215       6.0      416.0   1.0   2.0   
36600     1170  36601.0  0.438374       8.0      702.0   2.0   2.0   
18962     1170  18963.0  0.343015       2.0      128.0   2.0   5.0   
24240     1170  24241.0 -0.583535       4.0      224.0   2.0   5.0   
29535     1170  29536.0 -0.810176       6.0      312.0   2.0   5.0   
34628     1170  34629.0 -0.920059       8.0      390.0   2.0   5.0   
18969     1170  18970.0  0.185372       2.0      128.0   1.0   4.0   
25128     1170  25129.0  0.737069       4.0      255.0   2.0   4.0   
25149     1170  25150.0  0.747332       4.0      256.0   2.0   4.0   
31361     1170  31362.0  0.881173       6.0      467.0   2.0   4.0   
37025     1170  37026.0  0.948855       8.0      778.0   2.0   4.0   
19007     1170  19008.0  0.932562       2.0      128.0   1.0   3.0   
25142     1170  25143.0  0.849961       4.0      256.0   2.0   3.0   
31373     1170  31374.0  0.824937       6.0      468.0   2.0   3.0   
37032     1170  37033.0  0.811832       8.0      780.0   1.0   3.0   
19021     1170  19022.0  0.080903       2.0      128.0   2.0   1.0   
25123     1170  25124.0  0.106143       4.0      255.0   1.0   2.0   
25147     1170  25148.0  0.106471       4.0      256.0   2.0   2.0   
30801     1170  30802.0  0.113725       6.0      415.0   2.0   1.0   
36133     1170  

In [7]:
ideal_ch1 = []
ideal_x = []
ideal_y = []
ideal_z = []

In [8]:
def ideal_data(par_id):
    par_info = dff.loc[dff['particle_id']==par_id]
    ideal_ch1 = []
    ideal_x = []
    ideal_y = []
    ideal_z = []
    for s in np.unique(par_info['event_id']):
        particle_info = par_info.loc[par_info['event_id'] == s]   
        par_lay2, par_lay4, par_lay6 = particle_info.loc[particle_info['layer_id'] == 2], particle_info.loc[particle_info['layer_id'] == 4], particle_info.loc[particle_info['layer_id'] == 6]
        for i in range(len(par_lay2)):
            for j in range(len(par_lay4)):
                for k in range(len(par_lay6)):
                    data_lay2, data_lay4, data_lay6 = par_lay2.iloc[i,:], par_lay4.iloc[j,:], par_lay6.iloc[k, :] 
                    x_lay2, x_lay4, x_lay6 = data_lay2['x'], data_lay4['x'], data_lay6['x']
                    y_lay2, y_lay4, y_lay6 = data_lay2['y'], data_lay4['y'], data_lay6['y']
                    z_lay2, z_lay4, z_lay6 = data_lay2['z'], data_lay4['z'], data_lay6['z']
                    ch_lay2, ch_lay4, ch_lay6 = data_lay2['nch1'], data_lay4['nch1'], data_lay6['nch1']

                    ch1_1 = [ch_lay2, ch_lay4, ch_lay6]
                    x_1 = [x_lay2, x_lay4, x_lay6]
                    y_1 = [y_lay2, y_lay4, y_lay6]
                    z_1 = [z_lay2, z_lay4, z_lay6]
                    ideal_ch1.append(ch1_1)
                    ideal_x.append(x_1)
                    ideal_y.append(y_1)
                    ideal_z.append(z_1)
    return ideal_ch1, ideal_x, ideal_y, ideal_z



In [9]:
a, b, c, d = ideal_data(1.0358499045277696e+17)

In [10]:
a

[[1.0, 1.0, 1.0], [1.0, 2.0, 2.0], [2.0, 2.0, 1.0], [1.0, 2.0, 1.0]]

In [11]:
b

[[-32.528499603271484, -70.99539947509766, -113.96900177001953],
 [-31.67020034790039, -71.03260040283203, -114.8010025024414],
 [21.240999221801758, 46.975399017333984, 73.15699768066406],
 [21.995500564575195, 46.975399017333984, 73.15699768066406]]

In [12]:
c

[[-3.7227799892425537, -10.816300392150879, -22.086700439453125],
 [-4.677519798278809, -8.564390182495117, -10.61870002746582],
 [23.414199829101562, 54.575401306152344, 90.09120178222656],
 [24.299999237060547, 54.575401306152344, 90.09120178222656]]

In [13]:
d

[[-25.971900939941406, -17.534400939941406, -8.140629768371582],
 [6.115620136260986, 17.00429916381836, 29.118099212646484],
 [33.84339904785156, 22.240100860595703, 9.434379577636719],
 [33.5093994140625, 22.240100860595703, 9.434379577636719]]

In [14]:
dff.loc[dff['particle_id']==1.0358499045277696e+17]

event_id   hit_id       eta  layer_id  module_id  nch0  nch1  \
16039     1131  16040.0 -0.727394       2.0       97.0   2.0   1.0   
23411     1131  23412.0 -0.241799       4.0      193.0   1.0   1.0   
29528     1131  29529.0 -0.070066       6.0      314.0   1.0   1.0   
35450     1131  35451.0  0.019978       8.0      549.0   2.0   1.0   
35453     1131  35454.0  0.022032       8.0      550.0   1.0   1.0   
25317     1139  25318.0  0.189888       2.0      113.0   3.0   1.0   
34439     1139  34440.0  0.235484       4.0      225.0   2.0   2.0   
42379     1139  42380.0  0.249951       6.0      365.0   2.0   2.0   
49471     1139  49472.0  0.258433       8.0      547.0   2.0   2.0   
23401     1141  23402.0  0.930384       2.0      122.0   1.0   2.0   
23532     1141  23533.0  0.897099       2.0      123.0   2.0   1.0   
31796     1141  31797.0  0.304145       4.0      245.0   1.0   2.0   
39154     1141  39155.0  0.081204       6.0      398.0   2.0   1.0   
45107     1141  45108.0 -0.041690       8.0      519.0   1.0   1.0   

        particle_id       tpx       tpy       tpz  volume_id           x  \
16039  1.035850e+17 -0.341868 -0.050015  0.074649        8.0  -32.528500   
23411  1.035850e+17 -0.336085 -0.073940  0.074309        8.0  -70.995399   
29528  1.035850e+17 -0.329059 -0.100388  0.072091        8.0 -113.969002   
35450  1.035850e+17 -0.317544 -0.130892  0.071883        8.0 -166.074005   
35453  1.035850e+17 -0.316722 -0.132452  0.072455        8.0 -167.878998   
25317  1.035850e+17 -0.464198 -0.058188  0.125113        8.0  -31.670200   
34439  1.035850e+17 -0.464509 -0.033912  0.128858        8.0  -71.032600   
42379  1.035850e+17 -0.465382 -0.008699  0.127982        8.0 -114.801003   
49471  1.035850e+17 -0.463665  0.026211  0.128848        8.0 -171.141006   
23401  1.035850e+17  0.297001  0.342575 -0.127641        8.0   21.240999   
23532  1.035850e+17  0.296196  0.343293 -0.127421        8.0   21.995501   
31796  1.035850e+17  0.278603  0.355959 -0.130574        8.0   46.975399   
39154  1.035850e+17  0.257085  0.371056 -0.130982        8.0   73.156998   
45107  1.035850e+17  0.229326  0.387399 -0.133097        8.0  103.658997   

                y          z  
16039   -3.722780 -25.971901  
23411  -10.816300 -17.534401  
29528  -22.086700  -8.140630  
35450  -40.561401   3.415630  
35453  -41.300201   3.809380  
25317   -4.677520   6.115620  
34439   -8.564390  17.004299  
42379  -10.618700  29.118099  
49471   -9.493920  44.791199  
23401   23.414200  33.843399  
23532   24.299999  33.509399  
31796   54.575401  22.240101  
39154   90.091202   9.434380  
45107  137.604004  -7.184380

In [15]:
ideal_particle_ids[0]

1.6213817651992986e+17

In [16]:
ideal_data(1.6213817651992986e+17)

([[1.0, 1.0, 1.0], [2.0, 1.0, 1.0]],
 [[-33.51150131225586, -72.83560180664062, -115.93000030517578],
  [-32.03260040283203, -72.83560180664062, -115.93000030517578]],
 [[-0.9111539721488953, -3.236530065536499, -7.551219940185547],
  [-0.8400859832763672, -3.236530065536499, -7.551219940185547]],
 [[-23.215599060058594, -28.6156005859375, -34.6343994140625],
  [-23.00819969177246, -28.6156005859375, -34.6343994140625]])

In [17]:
ideal_x

[]

In [18]:
for par_id in ideal_particle_ids:    
    par_info = dff.loc[dff['particle_id']==par_id] 
    ch1s, xs, ys, zs = ideal_data(par_id)
    for ch1 in ch1s:
        ideal_ch1.append(ch1)
    for x in xs:
        ideal_x.append(x)
    for y in ys:
        ideal_y.append(y)
    for z in zs:
        ideal_z.append(z)

In [19]:
len(ideal_ch1)

112143

In [20]:
len(dff['particle_id'].unique())

33678

In [21]:
ideal_ch1

[[1.0, 1.0, 1.0],
 [2.0, 1.0, 1.0],
 [2.0, 1.0, 1.0],
 [2.0, 2.0, 1.0],
 [1.0, 1.0, 1.0],
 [1.0, 2.0, 1.0],
 [4.0, 3.0, 4.0],
 [4.0, 3.0, 4.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [5.0, 4.0, 4.0],
 [5.0, 4.0, 5.0],
 [5.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [4.0, 4.0, 5.0],
 [4.0, 4.0, 4.0],
 [2.0, 2.0, 2.0],
 [4.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [1.0, 2.0, 1.0],
 [5.0, 6.0, 5.0],
 [3.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0],
 [2.0, 2.0, 2.0],
 [2.0, 2.0, 2.0],
 [1.0, 2.0, 1.0],
 [5.0, 6.0, 5.0],
 [5.0, 6.0, 5.0],
 [2.0, 2.0, 2.0],
 [2.0, 2.0, 2.0],
 [4.0, 4.0, 4.0],
 [3.0, 4.0, 4.0],
 [6.0, 5.0, 6.0],
 [6.0, 5.0, 6.0],
 [1.0, 1.0, 1.0],
 [1.0, 1.0, 2.0],
 [3.0, 4.0, 3.0],
 [3.0, 4.0, 3.0],
 [2.0, 2.0, 1.0],
 [3.0, 3.0, 4.0],
 [3.0, 2.0, 2.0],
 [3.0, 3.0, 2.0],
 [3.0, 2.0, 2.0],
 [3.0, 3.0, 2.0],
 [2.0, 2.0, 2.0],
 [2.0, 3.0, 2.0],
 [1.0, 1.0, 1.0],
 [3.0, 3.0, 3.0],
 [3.0, 3.0, 3.0],
 [2.0, 2.0, 1.0],
 [3.0, 3.0, 3.0],
 [1.0, 2.0, 2.0],
 [1.0, 2.0, 2.0],
 [4.0, 4.0

In [22]:
np.save('f_ideal_ch1_number_7_cut.npy', np.array(ideal_ch1))
np.save('f_ideal_x_number_7_cut.npy', np.array(ideal_x))
np.save('f_ideal_y_number_7_cut.npy', np.array(ideal_y))
np.save('f_ideal_z_number_7_cut.npy', np.array(ideal_z))


In [23]:
ideal_x

[[-33.51150131225586, -72.83560180664062, -115.93000030517578],
 [-32.03260040283203, -72.83560180664062, -115.93000030517578],
 [-29.32229995727539, -66.40550231933594, -108.71499633789062],
 [-29.32229995727539, -68.47219848632812, -108.71499633789062],
 [-30.762699127197266, -66.40550231933594, -108.71499633789062],
 [-30.762699127197266, -68.47219848632812, -108.71499633789062],
 [6.0894999504089355, 11.173600196838379, 13.67959976196289],
 [6.0894999504089355, 11.173600196838379, 13.717599868774414],
 [23.399900436401367, 52.87409973144531, 86.7123031616211],
 [25.148500442504883, 52.87409973144531, 86.7123031616211],
 [29.655099868774414, 66.32689666748047, 107.60299682617188],
 [29.655099868774414, 66.32689666748047, 108.0739974975586],
 [29.655099868774414, 66.32689666748047, 109.98899841308594],
 [31.5137996673584, 66.32689666748047, 107.60299682617188],
 [31.5137996673584, 66.32689666748047, 108.0739974975586],
 [31.5137996673584, 66.32689666748047, 109.98899841308594],
 [-25

In [38]:
ideal_ch1 = np.load('f_ideal_ch1_number_7_cut.npy')
ideal_x = np.load('f_ideal_x_number_7_cut.npy')
ideal_y = np.load('f_ideal_y_number_7_cut.npy')
ideal_z = np.load('f_ideal_z_number_7_cut.npy')
len(ideal_ch1)

112143

In [25]:
43554 /40

1088.85

In [26]:
def difference_parameters(hit1, hit2):
    x1, y1, z1 = hit1[0], hit1[1], hit1[2]
    x2, y2, z2 = hit2[0], hit2[1], hit2[2]
    r1, r2 = np.sqrt(x1**2 + y1**2), np.sqrt(x2**2 + y2**2)
    phi1, phi2 = np.arctan2(y1, x1), np.arctan2(y2, x2)
    dphi = phi2 - phi1
    if dphi > np.pi:
        dphi -= 2*np.pi
    
    elif dphi < -np.pi:
        dphi += 2*np.pi
    dz = z2 - z1
    dr = r2 - r1
    
    phi_slope = dphi/dr
    z0 = z1 - r1 * dz/dr
    
    R1, R2 = np.sqrt(r1**2 + z1**2), np.sqrt(r2**2 + z2**2)
    theta1, theta2 = np.arccos(z1/R1), np.arccos(z2/R2)    
    eta1, eta2 = -np.log(np.tan(theta1/2.0)), -np.log(np.tan(theta2/2.0))
    deta = eta2 - eta1
    return [dphi, dz, dr, phi_slope, z0, deta]

def stronger_difference_parameters(hit1, hit2):
    x1, y1, z1 = hit1[0], hit1[1], hit1[2]
    x2, y2, z2 = hit2[0], hit2[1], hit2[2]
    r1, r2 = np.sqrt(x1**2 + y1**2), np.sqrt(x2**2 + y2**2)
    phi1, phi2 = np.arctan2(y1, x1), np.arctan2(y2, x2)
    dphi = phi2 - phi1
    if dphi > np.pi:
        dphi -= 2*np.pi
        
    elif dphi < -np.pi:
        dphi += 2*np.pi
    dz = z2 - z1
    dr = r2 - r1
    
    phi_slope = dphi/dr
    z0 = z1 - r1 * dz/dr
    
    R1, R2 = np.sqrt(r1**2 + z1**2), np.sqrt(r2**2 + z2**2)
    theta1, theta2 = np.arccos(z1/R1), np.arccos(z2/R2)    
    eta1, eta2 = -np.log(np.tan(theta1/2.0)), -np.log(np.tan(theta2/2.0))
    deta = eta2 - eta1
    return [dphi, dz, dr, phi_slope, z0, deta, z1, r1, phi1, eta1]

In [27]:
# contains the x, y, z coordinates of a hit on layer_2, layer_4, layer_6
ideals_layer2 = np.array([list(ideal_x[:,0]), list(ideal_y[:,0]), list(ideal_z[:,0])]).transpose()
ideals_layer4 = np.array([list(ideal_x[:,1]), list(ideal_y[:,1]), list(ideal_z[:,1])]).transpose()
ideals_layer6 = np.array([list(ideal_x[:,2]), list(ideal_y[:,2]), list(ideal_z[:,2])]).transpose()

In [28]:
ideal_x

array([[ -33.51150131,  -72.83560181, -115.93000031],
       [ -32.0326004 ,  -72.83560181, -115.93000031],
       [ -29.32229996,  -66.40550232, -108.71499634],
       ...,
       [ -31.13800049,  -69.63670349, -113.69799805],
       [ -31.13800049,  -71.73870087, -113.69799805],
       [ -30.96389961,  -71.03630066, -111.15200043]])

In [29]:
ideal_y

array([[ -0.91115397,  -3.23653007,  -7.55121994],
       [ -0.84008598,  -3.23653007,  -7.55121994],
       [-12.89290047, -26.8628006 , -39.38299942],
       ...,
       [  6.22912979,  14.56040001,  24.6548996 ],
       [  6.22912979,  15.01760006,  24.6548996 ],
       [  9.31532955, -16.88500023, -34.23400116]])

In [30]:
ideal_z

array([[-23.21559906, -28.61560059, -34.63439941],
       [-23.00819969, -28.61560059, -34.63439941],
       [-19.17149925, -22.4843998 , -26.36560059],
       ...,
       [  2.5718801 ,   7.56546021,  13.25940037],
       [  2.5718801 ,   7.81839991,  13.25940037],
       [ 23.54789925,  -3.4511199 , -28.81570053]])

In [31]:
ideals_layer2

array([[-33.51150131,  -0.91115397, -23.21559906],
       [-32.0326004 ,  -0.84008598, -23.00819969],
       [-29.32229996, -12.89290047, -19.17149925],
       ...,
       [-31.13800049,   6.22912979,   2.5718801 ],
       [-31.13800049,   6.22912979,   2.5718801 ],
       [-30.96389961,   9.31532955,  23.54789925]])

In [32]:
ideals_layer4

array([[-72.83560181,  -3.23653007, -28.61560059],
       [-72.83560181,  -3.23653007, -28.61560059],
       [-66.40550232, -26.8628006 , -22.4843998 ],
       ...,
       [-69.63670349,  14.56040001,   7.56546021],
       [-71.73870087,  15.01760006,   7.81839991],
       [-71.03630066, -16.88500023,  -3.4511199 ]])

In [34]:
ideal_difference_layer24 = []
for i, j in zip(ideals_layer2, ideals_layer4):
    ideal_24 = difference_parameters(i, j)
    ideal_difference_layer24.append(ideal_24)
ideal_difference_layer24 = np.array(ideal_difference_layer24)

In [40]:
ideal_difference_layer46 = []
for i, j in zip(ideals_layer4, ideals_layer6):
    ideal_46 = stronger_difference_parameters(i, j)
    ideal_difference_layer46.append(ideal_46)
ideal_difference_layer46 = np.array(ideal_difference_layer46)
np.save('f_ideal_diff_lay24_7_cut.npy', np.array(ideal_difference_layer24))
np.save('f_ideal_diff_lay46_7_cut.npy', np.array(ideal_difference_layer46))

In [41]:
ideal_difference_layer24 = np.load('f_ideal_diff_lay24_7_cut.npy')
ideal_difference_layer46 = np.load('f_ideal_diff_lay46_7_cut.npy')
ideal_difference_layer46

array([[ 2.06372589e-02, -6.01879883e+00,  4.32681925e+01, ...,
         7.29074757e+01, -3.09718577e+00, -3.83055321e-01],
       [ 2.06372589e-02, -6.01879883e+00,  4.32681925e+01, ...,
         7.29074757e+01, -3.09718577e+00, -3.83055321e-01],
       [-3.68485551e-02, -3.88120079e+00,  4.39954926e+01, ...,
         7.16330985e+01, -2.75719003e+00, -3.08944693e-01],
       ...,
       [-7.41813396e-03,  5.69394016e+00,  4.51978002e+01, ...,
         7.11426435e+01,  2.93547133e+00,  1.06142712e-01],
       [-7.18186454e-03,  5.44100046e+00,  4.30467228e+01, ...,
         7.32937208e+01,  2.93523506e+00,  1.06470891e-01],
       [ 6.54085546e-02, -2.53645806e+01,  4.32890158e+01, ...,
         7.30154726e+01, -2.90822792e+00, -4.72480158e-02]])

In [42]:
len(ideal_difference_layer24)

112143

In [ ]:
#indicator_test = np.array(list(trues_test) + list(falses_test))
actual_true = np.array([x for x, y in zip(decision_score,indicator_test) if y==1])
actual_false = np.array([x for x, y in zip(decision_score,indicator_test) if y==0])

In [ ]:
def roc_values(decision_scores):
    cuts = np.unique(decision_scores)
    tprs, fprs = [], []
    special_cuts, efficiencies, purities = [], [], []
    for cut in cuts:
        true_positive = np.array([i for i in actual_true if i >= cut])
        false_positive = np.array([i for i in actual_false if i >= cut])
        tpr, fpr = len(true_positive)/len(actual_true), len(false_positive)/len(actual_false)
        
        if abs(tpr-0.98) <= 0.02:
            efficiencies.append(tpr)
            purity = 1/(1+fpr/tpr*len(falses_test)/len(trues_test))
            purities.append(purity)
            special_cuts.append(cut)
            
        tprs.append(tpr)
        fprs.append(fpr)
    return np.array(tprs), np.array(fprs), np.array(special_cuts), np.array(efficiencies), np.array(purities)

In [ ]:
def purity_evaluation(tpr, fpr):
    purity = []
    for i in range(len(tpr)):
        if tpr[i] == 0:
            purity.append(0)
        else:
            purity.append(1/(1+fpr[i]/tpr[i]*len(falses_test)/len(trues_test)))
    return np.array(purity)